[phases.setup]
# better-sqlite3 için derleme araçları ve Canvas için font paketleri
nixPkgs = ["python3", "gcc", "gnumake", "fontconfig", "dejavu_fonts"]

[phases.install]
cmds = ["npm ci --build-from-source"]

[start]
cmd = "node index.js"
